name: Build and publish

# Run on PR requests. And on master itself.
on:
  push:
    branches:
      - master  # just build the sdist skip release
    tags:
      - "*"
  pull_request:  # also build on PRs touching some files
    paths:
      - ".github/workflows/release.yml"
      - "MANIFEST.in"
      - "setup.cfg"
      - "pyproject.toml"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build a source tarball
        run: |
          python -m pip install build
          python -m build

      - uses: actions/upload-artifact@v4
        with:
          path: ./dist/*
          retention-days: 5

  github-publish:
    name: Publish on GitHub
    needs: [build]
    runs-on: ubuntu-latest
    # release on every tag
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - name: Upload Github release
        id: upload-release-asset
        uses: softprops/action-gh-release@v2

  pypi-publish:
    name: Publish on PyPI
    needs: [build, github-publish]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/threedi-urban-eia-nl
    # release on every tag
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - name: Upload Release Assets to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1