name: Tests
on: [push, workflow_dispatch]
jobs:
  unittests:
    runs-on: ubuntu-latest

    name: Unit tests, Python ${{ matrix.python-version }}

    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install packages
        run: python -m pip install .[test]
      - name: Run unittests
        run: python -m pytest