# currently this package has no tests so we just check if it can be installed
name: Test package installation
on: [push, workflow_dispatch]
jobs:
  unittests:
    runs-on: ubuntu-latest

    name: Test package installation

    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install packages
        run: python -m pip install .